sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ###############
    access-key-secret: #############
    bucket-name: mtc-take-out
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 10
  wechat:
    appid: ##########
    secret: ################
    mchid: 1111
    mch-serial-no: 1
    private-key-file-path: 1111
    api-v3-key: 111
    we-chat-pay-cert-file-path: 1111
    notify-url: 111
    refund-notify-url: 1111
  shop:
    address: 北京东路
  baidu:
    ak: #################
